### ISSUE TITLE
Error Class Joomla\CMS\Form\Field\ListField not found

### ISSUE THREAD

**Issue by 4g0st1n0** [widgetfactory/jce#121]
**Describe the bug**
Error message "Class Joomla\CMS\Form\Field\ListField not found" when saving a profile. 
JCE latest version 2.9.51
Joomla! 3.10.12
PHP 8.1.2

I have reinstalled the 2.9.50 version and works correctly

**Comment by ryandemmer** [comment]
Fixed in commit - https://github.com/widgetfactory/jce/commit/205cb970d3cd28a67768202469e60f5ae28354cc

JCE Pro 2.9.51 Beta is available for testing - https://www.joomlacontenteditor.net/downloads/editor/pro/development

An update will be available next week.

**Comment by peterhulst** [comment]
In Joomla 3.10, I have installed 2.9.51 today (16 nov '23), but still 'Class 'Joomla\CMS\Form\Field\ListField' not found' is found is displayed after SAVE&CLOSE. Both with PHP 7.4 and 8.0.
With 2.9.50 the problem disappeared.
So it is NOT fixed yet.

(installing 2.9.53/54 does not help in my case, because than my changes are not stored. I have reported that in another issue #123)
